name: Mayhem
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2

      - name: Start analysis
        uses: ethan42/mcode-action@a3b1c8abe08b6626856e65c29c2674ca318a8d1f
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ethan42/lighttpd:pr-16 --corpus file://mayhem/corpus
          sarif-output: sarif


      - name: Upload SARIF file(s)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif
