name: Mayhem
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: Mayhem for Code
        uses: ethan42/mcode-action@81ed479fb95c250af4f9ff9cec5c50e310fd46d1
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          mayhem-url: ${{ secrets.MAYHEM_URL }}
          args: --image ${{ github.repository }}:${{ steps.branch-name.outputs.current_branch }} --corpus file://mayhem/corpus

      - name: Upload SARIF file(s)
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: mayhem-out/sarif
