name: Mayhem
on:
  workflow_dispatch:

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - uses: ethan42/mcode-action@d2f2c087c9ab142c1a85d89e2a9a25f2845e43ee
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          mayhem-url: ${{ secrets.MAYHEM_URL }}
          args: --image ${{ github.repository }}:${{ steps.branch-name.outputs.current_branch }} --corpus file://mayhem/corpus
