name: Mayhem
on:
  workflow_dispatch:

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - uses: ethan42/mcode-action@fc29e61f736d67551cc8f39246efd26c14ff0839
        with:
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          mayhem-url: ${{ secrets.MAYHEM_URL }}
          args: --image ${{ steps.branch-name.outputs.current_branch }}
